version: "3.8"
services:
  redchatservice:
    build:
      context: ./Backend
      dockerfile: TheRedChat/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - TheRedChat-db
    restart: always
    env_file:
      - Backend/.env

  TheRedChat-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data_redchat_final_sql_db:/var/opt/mssql

  redchat-frontend:
    build:
      context: ./Frontend/RedChatFrontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - redchatservice
    restart: always

volumes:
  mssql_data_redchat_final_sql_db:
